# Generated by Django 5.0.4 on 2024-07-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_item_address_alter_item_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='age',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='birth_date',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='birth_place',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='blood_type',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='civil_status',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='cizizenship',
            field=models.CharField(default='Philippines', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='company_address',
            field=models.TextField(default='default_value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='company_name',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='employee_num',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='gsis_num',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='occupation',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='pagibig_num',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='philhealth_num',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='sex',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='sss_num',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='telephone',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='tin_num',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='zip_code',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
    ]
